Updated dp-config-aks Charts and Values
syan-tibco/tp-helm-charts pull request #19
Opened 2023-08-24 10:56 UTC by sultaniap

2023-08-24 13:39 UTC, syan-tibco reviewed
As far as I konw event we will use controller to create ALB; Azure does not have ACM service and we need to manually attach to ALB. I would suggest avoiding other automation and just using main ingress to terminate SSL. 

Also we need to support TLS for messaging.

2023-08-24 13:39 UTC, syan-tibco commented on charts/dp-config-aks/values.yaml
> +  #       secretName: cic-certificate-production
I thought in this chart we terminate SSL on traefik side. If you comment this out; how do we provide certificate? Other automation might be needed.

2023-08-24 15:20 UTC, nashtapu-tibco requested changes
Some comments added.

2023-08-24 15:20 UTC, nashtapu-tibco commented on charts/dp-config-aks/values.yaml
> +    enabled: false
This should be set to "true", right?
Same for line 56.

2023-08-24 19:05 UTC, syan-tibco approved these changes

2023-08-25 03:20 UTC, sultaniap commented on charts/dp-config-aks/Chart.yaml
> +description: dp-config-aks is used to config CIC2 TIBCO Dataplane
changed it

2023-08-25 03:22 UTC, sultaniap commented on charts/dp-config-aks/values.yaml
> +    enabled: false
Had a Discussion with @syan-tibco and this will be set to false as when the customer wants it enabled , he can just enable it in the recipe before deployment 
Please see this - https://github.com/tibco/cicinfra-devops/blob/main/recipes/cp-platform-dev/DataPlane/poc/eks/2.dp-config-customer.yaml

2023-08-25 03:24 UTC, merged