PCP-2952 add custom footer on error page
syan-tibco/tp-helm-charts pull request #195
Opened 2023-12-11 19:33 UTC by snenkov-tibco

2023-12-11 19:57 UTC, ashundi-tibco requested changes
1. add screenshot in description
2. merge other changes from other PR so this is clean

2023-12-11 19:57 UTC, ashundi-tibco commented on charts/oauth2-proxy-manifests/values.yaml
> +  footer: "Secured by TIBCO Control Plane"
```suggestion
  footer: "Secured by TIBCO Platform"
```

2023-12-11 20:29 UTC, snenkov-tibco commented on charts/oauth2-proxy-manifests/values.yaml
> +  footer: "Secured by TIBCO Control Plane"
ok

2023-12-11 20:52 UTC, ashundi-tibco requested changes

2023-12-11 20:52 UTC, ashundi-tibco commented on charts/oauth2-proxy-manifests/templates/shell-script-cm.yaml
> +          echo "Failed to register client!"
```suggestion
          echo "Failed to register client: ${response}"
```

2023-12-11 20:52 UTC, ashundi-tibco commented on charts/oauth2-proxy-manifests/templates/shell-script-cm.yaml
> +        echo "Failed to register client!"
```suggestion
        echo "Invalid client value: ${clientId}"
```

2023-12-11 20:57 UTC, ashundi-tibco approved these changes

2023-12-12 00:56 UTC, ashundi-tibco approved these changes

2023-12-12 16:10 UTC, merged