Pdp 859 - added nginx IC in dp-config-aks
syan-tibco/tp-helm-charts pull request #56
Opened 2023-09-28 04:56 UTC by sultaniap

2023-09-28 05:40 UTC, nashtapu-tibco requested changes

2023-09-28 05:40 UTC, nashtapu-tibco commented on charts/dp-config-aks/values.yaml
>      external-dns.alpha.kubernetes.io/hostname: "*.cic20-tsc-dev-eu-rg-01.azrtroposdev.azure.tcie.pro"
Should we change the dns now to a simple one, removing cic20, tsc, eregion, subscription-name and make it more generic similar to AWS non-CIC2 DP?
cc: @syan-tibco

2023-09-28 05:40 UTC, nashtapu-tibco commented on charts/dp-config-aks/values.yaml
> +      kubernetes.io/os: linux
Do we have an assumption that we will have linux nodes only OR windows-linux mixed nodes in DP?

2023-09-28 05:40 UTC, nashtapu-tibco commented on charts/dp-config-aks/templates/ingress-http.yaml
> +    secretName: "{{.Values.tls.certificateSecretName}}"
Is secret namespace not required here? The Ingress is getting created in Release.Namespace and tls cert is in ingress-system namespace.

Also, on a different note, why don't we create this ingress in the nginx namespace and in release namespace?

2023-09-28 05:40 UTC, nashtapu-tibco commented on charts/dp-config-aks/templates/certificate-production.yaml
> +
May be, I am not getting it right, but why do we have if...else for tls.setup production?

2023-09-28 06:18 UTC, sultaniap commented on charts/dp-config-aks/values.yaml
> +      kubernetes.io/os: linux
We have assumed linux nodes for now, same as for AWS

2023-09-28 06:23 UTC, sultaniap commented on charts/dp-config-aks/templates/ingress-http.yaml
> +    secretName: "{{.Values.tls.certificateSecretName}}"
Secret and ingress both are created in release-namespace

2023-09-28 06:26 UTC, sultaniap commented on charts/dp-config-aks/templates/ingress-http.yaml
> +    secretName: "{{.Values.tls.certificateSecretName}}"
One upside is to create in release namespace is when we delete the dp-config-aks chart it will delete everything in that namespace

2023-09-28 15:12 UTC, syan-tibco approved these changes
you can make the change and submit it. We don't want to always on branch. We can always upgrade chart

2023-09-28 15:12 UTC, syan-tibco commented on charts/dp-config-aks/values.yaml
>      external-dns.alpha.kubernetes.io/hostname: "*.cic20-tsc-dev-eu-rg-01.azrtroposdev.azure.tcie.pro"
yeah, we should remove all cic20 default value.

2023-09-28 15:12 UTC, syan-tibco commented on charts/dp-config-aks/values.yaml
> +      kubernetes.io/os: linux
we can keep this for now. this was for cic2 cluster.

2023-09-28 17:34 UTC, sultaniap commented on charts/dp-config-aks/templates/certificate-production.yaml
> +
Removed

2023-09-28 17:35 UTC, sultaniap commented on charts/dp-config-aks/Chart.yaml
> +    condition: nginx.enabled
done

2023-09-29 07:43 UTC, sultaniap commented on charts/dp-config-aks/values.yaml
>      external-dns.alpha.kubernetes.io/hostname: "*.cic20-tsc-dev-eu-rg-01.azrtroposdev.azure.tcie.pro"
Done

2023-09-29 07:43 UTC, merged